Repository Mata-Elang-Stable/SnorqttAlpine-Sensor, pull requests merged in 2022-02, with the labels that each got.

#9 change function requirement
  developer-guide.md
  require/libs/snort_parser.py
Labels: documentation, enhancement

#4 Test get protocol from id()
  .gitignore
  require/libs/snort_parser.py
  require/requirements.txt
Labels: enhancement

#7 get_ip_detail_from_ethernet_data() function
  require/libs/snort_parser.py
Labels: enhancement

#11 Get ip detail and pkt info from ethernet data
  require/libs/snort_parser.py
Labels: enhancement

#12 fix the wrong assignment for get_protocol_from_id unit test function
  require/libs/snort_parser.py
Labels: bug

#13 separate unit test code into tests directory
  require/libs/snort_parser.py
  tests/__init__.py
  tests/test_snort_parser.py
Labels: enhancement

#14 improve code to make some parts more simple
  require/libs/snort_parser.py
  require/requirements.txt
Labels: enhancement

#15 test_get_ip_detail_from_ethernet_data
  tests/test_snort_parser.py
Labels: enhancement
